"""users table

Revision ID: a7cf62463ec8
Revises: f7694f8a621a
Create Date: 2022-03-07 08:13:34.277634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7cf62463ec8'
down_revision = 'f7694f8a621a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'todo',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'todo',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
