"""users table

Revision ID: cefd1dab6d8c
Revises: e8f5504110f2
Create Date: 2022-03-02 14:22:36.188533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cefd1dab6d8c'
down_revision = 'e8f5504110f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('time', sa.String(length=120), nullable=False))
    op.create_unique_constraint(None, 'user', ['time'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'time')
    # ### end Alembic commands ###
